version: '3.7'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    image: waves_client_prod
    container_name: waves_client_container_prod
    volumes:
      - ./client/:/usr/src/waves2020/client/
      - /usr/src/waves2020/client/node_modules
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - waves_network
    restart: always
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    image: waves_server_prod
    container_name: waves_server_container_prod
    restart: always
    command: npm run server
    volumes:
      - ./server/:/usr/src/waves2020/server/
      - /usr/src/waves2020/server/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/waves2020
    networks:
      - waves_network 
  mongo:
    image: mongo
    restart: always
    container_name: waves_mongo_container_prod
    ports:
      - '27017:27017'
    networks:
      - waves_network
    volumes:
      - data_mongo:/data/db

networks:
  waves_network:
      driver: bridge
    
volumes:
    data_mongo:
    node_modules:
    web-root:
      driver: local