version: '3.7'
services:
  client_reg_portal:
    stdin_open: true
    # build: 
    #   context: ./client
    #   dockerfile: Dockerfile.prod
    image: devsocbpgc/waves_client_reg_portal
    container_name: waves_client_reg_portal_container
    ports:
      - '3020:3000'
    depends_on:
      - api_reg_portal
    networks:
      - waves_network_reg_portal
    restart: always
  api_reg_portal:
    # build: 
    #   context: ./server
    #   dockerfile: Dockerfile.prod
    image: devsocbpgc/waves_server_reg_portal
    container_name: waves_server_reg_portal_container
    restart: always
    command: npm run server
    ports:
      - '5020:5000'
    depends_on:
      - mongo_reg_portal
    environment:
      - MONGO_URL=mongodb://mongo_reg_portal:27017/waves2020_reg_portal
    networks:
      - waves_network_reg_portal
  mongo_reg_portal:
    image: mongo
    restart: always
    container_name: waves_mongo_reg_portal_container
    ports:
      - '27019:27017'
    networks:
      - waves_network_reg_portal
    volumes:
      - ~/data_mongo_waves_reg_portal/db:/data/db

  # nginx_service:
  #   image: waves_nginx
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   depends_on:
  #     - client
  #     - api

networks:
  waves_network_reg_portal:
      driver: bridge
    
volumes:
    node_modules:
    web-root:
      driver: local